name: Create Pull Request

on: [push]

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create PR
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Automatically created pull request from workflow"
          title: "PR: [${{ github.ref_name }}]"
          body: |
            Branch: ${{ github.ref_name }}
            Author: ${{ github.actor }}
          branch: ${{ github.ref_name }}
          base: main
          labels: auto-pr
